window.displayPayload = {
   "features":{
      "id":"730",
      "slug":"web-css-display",
      "mdn_uri":{
         "en":"https://developer.mozilla.org/en-US/docs/Web/CSS/display",
         "de":"https://developer.mozilla.org/de/docs/Web/CSS/display",
         "es":"https://developer.mozilla.org/es/docs/Web/CSS/display",
         "fr":"https://developer.mozilla.org/fr/docs/Web/CSS/display",
         "ja":"https://developer.mozilla.org/ja/docs/Web/CSS/display",
         "pl":"https://developer.mozilla.org/pl/docs/Web/CSS/display",
         "pt-BR":"https://developer.mozilla.org/pt-BR/docs/Web/CSS/display",
         "pt-PT":"https://developer.mozilla.org/pt-PT/docs/Web/CSS/display",
         "ru":"https://developer.mozilla.org/ru/docs/Web/CSS/display",
         "zh-CN":"https://developer.mozilla.org/zh-CN/docs/CSS/display"
      },
      "experimental":false,
      "standardized":true,
      "stable":true,
      "obsolete":false,
      "name":"display",
      "links":{
         "sections":[
            "8",
            "9",
            "7",
            "12",
            "10",
            "11"
         ],
         "supports":[

         ],
         "parent":"581",
         "children":[

         ]
      }
   },
   "linked":{
      "browsers":[
         {
            "id":"1",
            "slug":"android",
            "name":{
               "en":"Android"
            },
            "note":null
         },
         {
            "id":"10",
            "slug":"internet_explorer",
            "name":{
               "en":"Internet Explorer"
            },
            "note":null
         },
         {
            "id":"11",
            "slug":"opera",
            "name":{
               "en":"Opera"
            },
            "note":null
         },
         {
            "id":"13",
            "slug":"opera_mobile",
            "name":{
               "en":"Opera Mobile"
            },
            "note":null
         },
         {
            "id":"14",
            "slug":"safari",
            "name":{
               "en":"Safari"
            },
            "note":null
         },
         {
            "id":"15",
            "slug":"safari_mobile",
            "name":{
               "en":"Safari Mobile"
            },
            "note":null
         },
         {
            "id":"3",
            "slug":"chrome",
            "name":{
               "en":"Chrome"
            },
            "note":null
         },
         {
            "id":"6",
            "slug":"firefox",
            "name":{
               "en":"Firefox"
            },
            "note":null
         },
         {
            "id":"7",
            "slug":"firefox_mobile",
            "name":{
               "en":"Firefox Mobile"
            },
            "note":null
         },
         {
            "id":"9",
            "slug":"ie_mobile",
            "name":{
               "en":"IE Mobile"
            },
            "note":null
         }
      ],
      "versions":[
         {
            "id":"14",
            "version":"4.4",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":13,
            "links":{
               "browser":"1"
            }
         },
         {
            "id":"151",
            "version":"current",
            "release_day":null,
            "retirement_day":null,
            "status":"current",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"156",
            "version":"4.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":5,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"159",
            "version":"5.5",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":8,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"160",
            "version":"6.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":9,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"162",
            "version":"8.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":11,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"164",
            "version":"10.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":13,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"165",
            "version":"11.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":14,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"166",
            "version":"current",
            "release_day":null,
            "retirement_day":null,
            "status":"current",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"11"
            }
         },
         {
            "id":"176",
            "version":"7.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":10,
            "links":{
               "browser":"11"
            }
         },
         {
            "id":"20",
            "version":"current",
            "release_day":null,
            "retirement_day":null,
            "status":"current",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"202",
            "version":"12.50",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":36,
            "links":{
               "browser":"11"
            }
         },
         {
            "id":"21",
            "version":"1.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":1,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"235",
            "version":"current",
            "release_day":null,
            "retirement_day":null,
            "status":"current",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"236",
            "version":"1.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":1,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"24",
            "version":"4.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":4,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"246",
            "version":"5.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":11,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"250",
            "version":"6.1",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":15,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"265",
            "version":"7.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":11,
            "links":{
               "browser":"15"
            }
         },
         {
            "id":"268",
            "version":"18.0",
            "release_day":"2013-01-08",
            "retirement_day":"2013-02-19",
            "status":"retired",
            "release_notes_uri":{
               "zh-CN":"https://developer.mozilla.org/zh-CN/Firefox/Releases/18",
               "pt-PT":"https://developer.mozilla.org/pt-PT/Firefox/Releases/18",
               "pl":"https://developer.mozilla.org/pl/Firefox/Releases/18",
               "ko":"https://developer.mozilla.org/ko/Firefox/Releases/18",
               "de":"https://developer.mozilla.org/de/Firefox/Releases/18",
               "zh-TW":"https://developer.mozilla.org/zh-TW/Firefox/Releases/18",
               "ru":"https://developer.mozilla.org/ru/Firefox/Releases/18",
               "en":"https://developer.mozilla.org/en/Firefox/Releases/18",
               "ja":"https://developer.mozilla.org/ja/Firefox/Releases/18",
               "fr":"https://developer.mozilla.org/fr/Firefox/Versions/18",
               "es":"https://developer.mozilla.org/es/Firefox/Releases/18"
            },
            "note":null,
            "order":21,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"275",
            "version":"34.0",
            "release_day":"2014-12-01",
            "retirement_day":"2015-01-12",
            "status":"retired",
            "release_notes_uri":{
               "zh-CN":"https://developer.mozilla.org/zh-CN/Firefox/Releases/34",
               "pt-PT":"https://developer.mozilla.org/pt-PT/Firefox/Releases/34",
               "es":"https://developer.mozilla.org/es/Firefox/Releases/34",
               "ko":"https://developer.mozilla.org/ko/Firefox/Releases/34",
               "de":"https://developer.mozilla.org/de/Firefox/Releases/34",
               "zh-TW":"https://developer.mozilla.org/zh-TW/Firefox/Releases/34",
               "ru":"https://developer.mozilla.org/ru/Firefox/Releases/34",
               "en":"https://developer.mozilla.org/en/Firefox/Releases/34",
               "ja":"https://developer.mozilla.org/ja/Firefox/Releases/34",
               "fr":"https://developer.mozilla.org/fr/Firefox/Releases/34",
               "pl":"https://developer.mozilla.org/pl/Firefox/Releases/34"
            },
            "note":null,
            "order":37,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"279",
            "version":"37.0",
            "release_day":"2015-03-31",
            "retirement_day":"2015-05-12",
            "status":"retired",
            "release_notes_uri":{
               "en":"https://developer.mozilla.org/en-US/Firefox/Releases/36"
            },
            "note":null,
            "order":40,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"41",
            "version":"21.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":21,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"52",
            "version":"32.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":32,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"67",
            "version":"current",
            "release_day":null,
            "retirement_day":null,
            "status":"current",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"68",
            "version":"1.0",
            "release_day":"2004-11-09",
            "retirement_day":"2005-11-29",
            "status":"retired",
            "release_notes_uri":null,
            "note":null,
            "order":1,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"73",
            "version":"3.0",
            "release_day":"2008-06-17",
            "retirement_day":"2009-06-30",
            "status":"retired",
            "release_notes_uri":{
               "zh-CN":"https://developer.mozilla.org/zh-CN/Firefox/Releases/3",
               "pt-PT":"https://developer.mozilla.org/pt-PT/Firefox/Releases/3",
               "pl":"https://developer.mozilla.org/pl/Firefox/Releases/3",
               "ko":"https://developer.mozilla.org/ko/Firefox/Releases/3",
               "de":"https://developer.mozilla.org/de/docs/Firefox_3_f%C3%BCr_Entwickler",
               "zh-TW":"https://developer.mozilla.org/zh-TW/docs/Firefox_3_for_developers",
               "ru":"https://developer.mozilla.org/ru/docs/Firefox_3_for_developers",
               "en":"https://developer.mozilla.org/en/Firefox/Releases/3",
               "ja":"https://developer.mozilla.org/ja/Firefox/Releases/3",
               "fr":"https://developer.mozilla.org/fr/Firefox/Versions/3",
               "es":"https://developer.mozilla.org/es/docs/Firefox_3_para_desarrolladores"
            },
            "note":null,
            "order":4,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"89",
            "version":"20.0",
            "release_day":"2013-04-02",
            "retirement_day":"2013-05-14",
            "status":"retired",
            "release_notes_uri":{
               "zh-CN":"https://developer.mozilla.org/zh-CN/Firefox/Releases/20",
               "pt-PT":"https://developer.mozilla.org/pt-PT/Firefox/Releases/20",
               "pl":"https://developer.mozilla.org/pl/Firefox/Releases/20",
               "ko":"https://developer.mozilla.org/ko/Firefox/Releases/20",
               "de":"https://developer.mozilla.org/de/Firefox/Releases/20",
               "zh-TW":"https://developer.mozilla.org/zh-TW/Firefox/Releases/20",
               "ru":"https://developer.mozilla.org/ru/Firefox/Releases/20",
               "en":"https://developer.mozilla.org/en/Firefox/Releases/20",
               "ja":"https://developer.mozilla.org/ja/Firefox/Releases/20",
               "fr":"https://developer.mozilla.org/fr/Firefox/Versions/20",
               "es":"https://developer.mozilla.org/es/Firefox/Releases/20"
            },
            "note":null,
            "order":23,
            "links":{
               "browser":"6"
            }
         }
      ],
      "supports":[
         {
            "id":"113",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"14",
               "feature":"1140"
            }
         },
         {
            "id":"114",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"265",
               "feature":"1140"
            }
         },
         {
            "id":"115",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"165",
               "feature":"1142"
            }
         },
         {
            "id":"116",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"250",
               "feature":"1142"
            }
         },
         {
            "id":"117",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"165",
               "feature":"1145"
            }
         },
         {
            "id":"118",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"250",
               "feature":"1145"
            }
         },
         {
            "id":"37",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"20",
               "feature":"1141"
            }
         },
         {
            "id":"38",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"In Firefox 36, it the preference governing this feature was off by default."
            },
            "links":{
               "version":"279",
               "feature":"1141"
            }
         },
         {
            "id":"39",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"151",
               "feature":"1141"
            }
         },
         {
            "id":"40",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"166",
               "feature":"1141"
            }
         },
         {
            "id":"41",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"235",
               "feature":"1141"
            }
         },
         {
            "id":"42",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"41",
               "feature":"1142"
            }
         },
         {
            "id":"43",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28."
            },
            "links":{
               "version":"268",
               "feature":"1142"
            }
         },
         {
            "id":"44",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"89",
               "feature":"1142"
            }
         },
         {
            "id":"46",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"202",
               "feature":"1142"
            }
         },
         {
            "id":"48",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"67",
               "feature":"1143"
            }
         },
         {
            "id":"49",
            "support":"yes",
            "prefix":"-ms",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"164",
               "feature":"1143"
            }
         },
         {
            "id":"50",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"21",
               "feature":"1144"
            }
         },
         {
            "id":"51",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"73",
               "feature":"1144"
            }
         },
         {
            "id":"52",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"Natural inline elements only"
            },
            "links":{
               "version":"159",
               "feature":"1144"
            }
         },
         {
            "id":"53",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"176",
               "feature":"1144"
            }
         },
         {
            "id":"54",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"236",
               "feature":"1144"
            }
         },
         {
            "id":"55",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"41",
               "feature":"1145"
            }
         },
         {
            "id":"56",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28."
            },
            "links":{
               "version":"268",
               "feature":"1145"
            }
         },
         {
            "id":"57",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"89",
               "feature":"1145"
            }
         },
         {
            "id":"59",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"202",
               "feature":"1145"
            }
         },
         {
            "id":"61",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"67",
               "feature":"1146"
            }
         },
         {
            "id":"62",
            "support":"yes",
            "prefix":"-ms",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"164",
               "feature":"1146"
            }
         },
         {
            "id":"63",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"21",
               "feature":"1147"
            }
         },
         {
            "id":"64",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"73",
               "feature":"1147"
            }
         },
         {
            "id":"65",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"162",
               "feature":"1147"
            }
         },
         {
            "id":"66",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"176",
               "feature":"1147"
            }
         },
         {
            "id":"67",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"236",
               "feature":"1147"
            }
         },
         {
            "id":"68",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"21",
               "feature":"1148"
            }
         },
         {
            "id":"69",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"68",
               "feature":"1148"
            }
         },
         {
            "id":"70",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"160",
               "feature":"1148"
            }
         },
         {
            "id":"71",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"176",
               "feature":"1148"
            }
         },
         {
            "id":"72",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"236",
               "feature":"1148"
            }
         },
         {
            "id":"73",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"21",
               "feature":"1149"
            }
         },
         {
            "id":"74",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"68",
               "feature":"1149"
            }
         },
         {
            "id":"75",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"156",
               "feature":"1149"
            }
         },
         {
            "id":"76",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"176",
               "feature":"1149"
            }
         },
         {
            "id":"77",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"236",
               "feature":"1149"
            }
         },
         {
            "id":"78",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"CSS Ruby support is behind pref \"layout.css.ruby.enabled\". The user has to change this pref to true to activate this."
            },
            "links":{
               "version":"275",
               "feature":"1150"
            }
         },
         {
            "id":"79",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"Not before inline-elements"
            },
            "links":{
               "version":"21",
               "feature":"1151"
            }
         },
         {
            "id":"80",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"52",
               "feature":"1151"
            }
         },
         {
            "id":"81",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"24",
               "feature":"1151"
            }
         },
         {
            "id":"82",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"67",
               "feature":"1151"
            }
         },
         {
            "id":"83",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"162",
               "feature":"1151"
            }
         },
         {
            "id":"84",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"176",
               "feature":"1151"
            }
         },
         {
            "id":"85",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":{
               "en":"Not before inline-elements"
            },
            "links":{
               "version":"236",
               "feature":"1151"
            }
         },
         {
            "id":"86",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"246",
               "feature":"1151"
            }
         },
         {
            "id":"87",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"21",
               "feature":"1152"
            }
         },
         {
            "id":"88",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"68",
               "feature":"1152"
            }
         },
         {
            "id":"89",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"162",
               "feature":"1152"
            }
         },
         {
            "id":"90",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"176",
               "feature":"1152"
            }
         },
         {
            "id":"91",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "links":{
               "version":"236",
               "feature":"1152"
            }
         }
      ],
      "maturities":[
         {
            "id":"1",
            "slug":"WD",
            "name":{
               "de":"Arbeitsentwurf",
               "en":"Working Draft",
               "ja":"\u8349\u6848",
               "fr":"Version de travail",
               "ru":"\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0447\u0435\u0440\u043d\u043e\u0432\u0438\u043a"
            }
         },
         {
            "id":"12",
            "slug":"LC",
            "name":{
               "en":"Last Call Working Draft"
            }
         },
         {
            "id":"4",
            "slug":"REC",
            "name":{
               "de":"Empfehlung",
               "en":"Recommendation",
               "ja":"\u52e7\u544a",
               "fr":"Recommendation",
               "ru":"\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f"
            }
         }
      ],
      "specifications":[
         {
            "id":"10",
            "slug":"css2_1",
            "mdn_key":"CSS2.1",
            "name":{
               "en":"CSS Level&nbsp;2 (Revision&nbsp;1)"
            },
            "uri":{
               "en":"http://www.w3.org/TR/CSS2/"
            },
            "links":{
               "maturity":"4",
               "sections":[
                  "3",
                  "8"
               ]
            }
         },
         {
            "id":"151",
            "slug":"css3_display",
            "mdn_key":"CSS3 Display",
            "name":{
               "en":"CSS Display Module Level&nbsp;3"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css-display/"
            },
            "links":{
               "maturity":"1",
               "sections":[
                  "9"
               ]
            }
         },
         {
            "id":"23",
            "slug":"css3_flexbox",
            "mdn_key":"CSS3 Flexbox",
            "name":{
               "en":"CSS Flexible Box Layout Module"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css3-flexbox/"
            },
            "links":{
               "maturity":"12",
               "sections":[
                  "10"
               ]
            }
         },
         {
            "id":"27",
            "slug":"css3_grid",
            "mdn_key":"CSS3 Grid",
            "name":{
               "en":"CSS Grid Layout"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css-grid/"
            },
            "links":{
               "maturity":"1",
               "sections":[
                  "11"
               ]
            }
         },
         {
            "id":"37",
            "slug":"css3_ruby",
            "mdn_key":"CSS3 Ruby",
            "name":{
               "en":"CSS Ruby Layout Module Level&nbsp;1"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css-ruby/"
            },
            "links":{
               "maturity":"1",
               "sections":[
                  "12"
               ]
            }
         },
         {
            "id":"9",
            "slug":"css1",
            "mdn_key":"CSS1",
            "name":{
               "en":"CSS Level&nbsp;1"
            },
            "uri":{
               "en":"http://www.w3.org/TR/CSS1/"
            },
            "links":{
               "maturity":"4",
               "sections":[
                  "2",
                  "7"
               ]
            }
         }
      ],
      "sections":[
         {
            "id":"10",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#flex-containers"
            },
            "note":{
               "en":"Added the flexible box model values."
            },
            "links":{
               "specification":"23"
            }
         },
         {
            "id":"11",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#grid-declaration0"
            },
            "note":{
               "en":"Added the grid box model values."
            },
            "links":{
               "specification":"27"
            }
         },
         {
            "id":"12",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#display"
            },
            "note":{
               "en":"Added the <code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, and <code>ruby-text-container</code>"
            },
            "links":{
               "specification":"37"
            }
         },
         {
            "id":"7",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#display"
            },
            "note":{
               "en":"Basic values: <code>none</code>, <code>block</code>, <code>inline</code>, and <code>list-item</code>."
            },
            "links":{
               "specification":"9"
            }
         },
         {
            "id":"8",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"visuren.html#display-prop"
            },
            "note":{
               "en":"Added the table model values and <code>inline-block<em>.</em></code>"
            },
            "links":{
               "specification":"10"
            }
         },
         {
            "id":"9",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#display"
            },
            "note":{
               "en":"Added the <code>run-in</code> and <code>contents</code> values."
            },
            "links":{
               "specification":"151"
            }
         }
      ],
      "features":[
         {
            "id":"1140",
            "slug":"web-css-display_basic_support",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"Basic support"
            },
            "links":{
               "sections":[

               ],
               "supports":[
                  "113",
                  "114"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1141",
            "slug":"web-css-display_contents",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"contents",
            "links":{
               "sections":[

               ],
               "supports":[
                  "37",
                  "38",
                  "39",
                  "40",
                  "41"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1142",
            "slug":"web-css-display_flex",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"flex",
            "links":{
               "sections":[

               ],
               "supports":[
                  "42",
                  "43",
                  "44",
                  "45",
                  "46",
                  "47",
                  "115",
                  "116"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1143",
            "slug":"web-css-display_grid",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"grid",
            "links":{
               "sections":[

               ],
               "supports":[
                  "48",
                  "49"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1144",
            "slug":"web-css-display_inline-block",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-block",
            "links":{
               "sections":[

               ],
               "supports":[
                  "50",
                  "51",
                  "52",
                  "53",
                  "54"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1145",
            "slug":"web-css-display_inline-flex",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-flex",
            "links":{
               "sections":[

               ],
               "supports":[
                  "55",
                  "56",
                  "57",
                  "58",
                  "59",
                  "60",
                  "117",
                  "118"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1146",
            "slug":"web-css-display_inline-grid",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-grid",
            "links":{
               "sections":[

               ],
               "supports":[
                  "61",
                  "62"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1147",
            "slug":"web-css-display_inline-table",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-table",
            "links":{
               "sections":[

               ],
               "supports":[
                  "63",
                  "64",
                  "65",
                  "66",
                  "67"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1148",
            "slug":"web-css-display_list-item",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"list-item",
            "links":{
               "sections":[

               ],
               "supports":[
                  "68",
                  "69",
                  "70",
                  "71",
                  "72"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1149",
            "slug":"web-css-display_none_inline_and_block",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"<code>none</code>, <code>inline</code> and <code>block</code>"
            },
            "links":{
               "sections":[

               ],
               "supports":[
                  "73",
                  "74",
                  "75",
                  "76",
                  "77"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1150",
            "slug":"web-css-display_ruby_ruby-base_ruby-text_ruby-base",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"<code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, <code>ruby-text-container</code>"
            },
            "links":{
               "sections":[

               ],
               "supports":[
                  "78"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1151",
            "slug":"web-css-display_run-in",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"run-in",
            "links":{
               "sections":[

               ],
               "supports":[
                  "79",
                  "80",
                  "81",
                  "82",
                  "83",
                  "84",
                  "85",
                  "86"
               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"1152",
            "slug":"web-css-display_table_table-cell_table-column_tabl",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"<code>table</code>, <code>table-cell</code>, <code>table-column</code>, <code>table-column-group</code>, <code>table-header-group</code>, <code>table-row-group</code>, <code>table-footer-group</code>, <code>table-row</code>, and <code>table-caption</code>"
            },
            "links":{
               "sections":[

               ],
               "supports":[
                  "87",
                  "88",
                  "89",
                  "90",
                  "91"
               ],
               "parent":"730",
               "children":[

               ]
            }
         }
      ]
   },
   "meta":{
      "compat_table":{
         "supports":{
            "730":{

            },
            "1149":{
               "3":[
                  73
               ],
               "6":[
                  74
               ],
               "10":[
                  75
               ],
               "11":[
                  76
               ],
               "14":[
                  77
               ]
            },
            "1144":{
               "3":[
                  50
               ],
               "6":[
                  51
               ],
               "10":[
                  52
               ],
               "11":[
                  53
               ],
               "14":[
                  54
               ]
            },
            "1148":{
               "3":[
                  68
               ],
               "6":[
                  69
               ],
               "10":[
                  70
               ],
               "11":[
                  71
               ],
               "14":[
                  72
               ]
            },
            "1151":{
               "3":[
                  79,
                  81,
                  80
               ],
               "6":[
                  82
               ],
               "10":[
                  83
               ],
               "11":[
                  84
               ],
               "14":[
                  85,
                  86
               ]
            },
            "1147":{
               "3":[
                  63
               ],
               "6":[
                  64
               ],
               "10":[
                  65
               ],
               "11":[
                  66
               ],
               "14":[
                  67
               ]
            },
            "1152":{
               "3":[
                  87
               ],
               "6":[
                  88
               ],
               "10":[
                  89
               ],
               "11":[
                  90
               ],
               "14":[
                  91
               ]
            },
            "1142":{
               "3":[
                  42
               ],
               "6":[
                  43,
                  44
               ],
               "10":[
                  115
               ],
               "11":[
                  46
               ],
               "14":[
                  116
               ]
            },
            "1145":{
               "3":[
                  55
               ],
               "6":[
                  56,
                  57
               ],
               "10":[
                  117
               ],
               "11":[
                  59
               ],
               "14":[
                  118
               ]
            },
            "1143":{
               "6":[
                  48
               ],
               "10":[
                  49
               ]
            },
            "1146":{
               "6":[
                  61
               ],
               "10":[
                  62
               ]
            },
            "1150":{
               "6":[
                  78
               ]
            },
            "1141":{
               "3":[
                  37
               ],
               "6":[
                  38
               ],
               "10":[
                  39
               ],
               "11":[
                  40
               ],
               "14":[
                  41
               ]
            },
            "1140":{
               "1":[
                  113
               ],
               "15":[
                  114
               ]
            }
         },
         "tabs":[
            {
               "name":{
                  "en":"Desktop Browsers"
               },
               "browsers":[
                  "3",
                  "6",
                  "10",
                  "11",
                  "14"
               ]
            },
            {
               "name":{
                  "en":"Mobile Browsers"
               },
               "browsers":[
                  "1",
                  "7",
                  "9",
                  "13",
                  "15"
               ]
            }
         ],
         "pagination":{

         },
         "languages":[
            "en",
            "de",
            "es",
            "fr",
            "ja",
            "pl",
            "pt-BR",
            "pt-PT",
            "ru",
            "zh-CN"
         ],
         "notes":{
            "52":1,
            "79":2,
            "85":3,
            "43":4,
            "56":5,
            "78":6,
            "38":7
         }
      },
      "scrape":{
         "phase":"Parsing Complete",
         "issues":[

         ],
         "raw":{
            "locale":"en",
            "specs":[
               {
                  "section.note":"Added the <code>run-in</code> and <code>contents</code> values.",
                  "section.name":"display",
                  "section.subpath":"#display",
                  "specification.id":151,
                  "specification.mdn_key":"CSS3 Display",
                  "section.id":9
               },
               {
                  "section.note":"Added the <code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, and <code>ruby-text-container</code>",
                  "section.name":"display",
                  "section.subpath":"#display",
                  "specification.id":37,
                  "specification.mdn_key":"CSS3 Ruby",
                  "section.id":12
               },
               {
                  "section.note":"Added the grid box model values.",
                  "section.name":"display",
                  "section.subpath":"#grid-declaration0",
                  "specification.id":27,
                  "specification.mdn_key":"CSS3 Grid",
                  "section.id":11
               },
               {
                  "section.note":"Added the flexible box model values.",
                  "section.name":"display",
                  "section.subpath":"#flex-containers",
                  "specification.id":23,
                  "specification.mdn_key":"CSS3 Flexbox",
                  "section.id":10
               },
               {
                  "section.note":"Added the table model values and <code>inline-block<em>.</em></code>",
                  "section.name":"display",
                  "section.subpath":"visuren.html#display-prop",
                  "specification.id":10,
                  "specification.mdn_key":"CSS2.1",
                  "section.id":8
               },
               {
                  "section.note":"Basic values: <code>none</code>, <code>block</code>, <code>inline</code>, and <code>list-item</code>.",
                  "section.name":"display",
                  "section.subpath":"#display",
                  "specification.id":9,
                  "specification.mdn_key":"CSS1",
                  "section.id":7
               }
            ],
            "compat":[
               {
                  "browsers":[
                     {
                        "name":"Chrome",
                        "slug":"chrome",
                        "id":3
                     },
                     {
                        "name":"Firefox",
                        "slug":"firefox",
                        "id":6
                     },
                     {
                        "name":"Internet Explorer",
                        "slug":"internet_explorer",
                        "id":10
                     },
                     {
                        "name":"Opera",
                        "slug":"opera",
                        "id":11
                     },
                     {
                        "name":"Safari",
                        "slug":"safari",
                        "id":14
                     }
                  ],
                  "versions":[
                     {
                        "browser":3,
                        "version":"1.0",
                        "id":21
                     },
                     {
                        "browser":6,
                        "version":"1.0",
                        "id":68
                     },
                     {
                        "browser":10,
                        "version":"4.0",
                        "id":156
                     },
                     {
                        "browser":11,
                        "version":"7.0",
                        "id":176
                     },
                     {
                        "browser":14,
                        "version":"1.0",
                        "id":236
                     },
                     {
                        "browser":6,
                        "version":"3.0",
                        "id":73
                     },
                     {
                        "browser":10,
                        "version":"5.5",
                        "id":159
                     },
                     {
                        "browser":10,
                        "version":"6.0",
                        "id":160
                     },
                     {
                        "browser":6,
                        "version":"current",
                        "id":67
                     },
                     {
                        "browser":10,
                        "version":"8.0",
                        "id":162
                     },
                     {
                        "browser":3,
                        "version":"4.0",
                        "id":24
                     },
                     {
                        "browser":3,
                        "version":"32.0",
                        "id":52
                     },
                     {
                        "browser":14,
                        "version":"5.0",
                        "id":246
                     },
                     {
                        "browser":3,
                        "version":"21.0",
                        "id":41
                     },
                     {
                        "browser":6,
                        "version":"18.0",
                        "id":268
                     },
                     {
                        "browser":6,
                        "version":"20.0",
                        "id":89
                     },
                     {
                        "browser":10,
                        "version":"11.0",
                        "id":165
                     },
                     {
                        "browser":11,
                        "version":"12.50",
                        "id":202
                     },
                     {
                        "browser":14,
                        "version":"6.1",
                        "id":250
                     },
                     {
                        "browser":10,
                        "version":"10.0",
                        "id":164
                     },
                     {
                        "browser":6,
                        "version":"34.0",
                        "id":275
                     },
                     {
                        "browser":3,
                        "version":"current",
                        "id":20
                     },
                     {
                        "browser":6,
                        "version":"37.0",
                        "id":279
                     },
                     {
                        "browser":10,
                        "version":"current",
                        "id":151
                     },
                     {
                        "browser":11,
                        "version":"current",
                        "id":166
                     },
                     {
                        "browser":14,
                        "version":"current",
                        "id":235
                     }
                  ],
                  "name":"desktop",
                  "features":[
                     {
                        "slug":"web-css-display_none_inline_and_block",
                        "name":"<code>none</code>, <code>inline</code> and <code>block</code>",
                        "id":1149
                     },
                     {
                        "slug":"web-css-display_inline-block",
                        "canonical":true,
                        "name":"inline-block",
                        "id":1144
                     },
                     {
                        "slug":"web-css-display_list-item",
                        "canonical":true,
                        "name":"list-item",
                        "id":1148
                     },
                     {
                        "slug":"web-css-display_run-in",
                        "canonical":true,
                        "name":"run-in",
                        "id":1151,
                        "experimental":true
                     },
                     {
                        "slug":"web-css-display_inline-table",
                        "canonical":true,
                        "name":"inline-table",
                        "id":1147
                     },
                     {
                        "slug":"web-css-display_table_table-cell_table-column_tabl",
                        "name":"<code>table</code>, <code>table-cell</code>, <code>table-column</code>, <code>table-column-group</code>, <code>table-header-group</code>, <code>table-row-group</code>, <code>table-footer-group</code>, <code>table-row</code>, and <code>table-caption</code>",
                        "id":1152
                     },
                     {
                        "slug":"web-css-display_flex",
                        "canonical":true,
                        "name":"flex",
                        "id":1142
                     },
                     {
                        "slug":"web-css-display_inline-flex",
                        "canonical":true,
                        "name":"inline-flex",
                        "id":1145
                     },
                     {
                        "slug":"web-css-display_grid",
                        "canonical":true,
                        "name":"grid",
                        "id":1143,
                        "experimental":true
                     },
                     {
                        "slug":"web-css-display_inline-grid",
                        "canonical":true,
                        "name":"inline-grid",
                        "id":1146,
                        "experimental":true
                     },
                     {
                        "slug":"web-css-display_ruby_ruby-base_ruby-text_ruby-base",
                        "name":"<code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, <code>ruby-text-container</code>",
                        "id":1150,
                        "experimental":true
                     },
                     {
                        "slug":"web-css-display_contents",
                        "canonical":true,
                        "name":"contents",
                        "id":1141,
                        "experimental":true
                     }
                  ],
                  "supports":[
                     {
                        "support":"yes",
                        "feature":1149,
                        "version":21,
                        "id":73
                     },
                     {
                        "support":"yes",
                        "feature":1149,
                        "version":68,
                        "id":74
                     },
                     {
                        "support":"yes",
                        "feature":1149,
                        "version":156,
                        "id":75
                     },
                     {
                        "support":"yes",
                        "feature":1149,
                        "version":176,
                        "id":76
                     },
                     {
                        "support":"yes",
                        "feature":1149,
                        "version":236,
                        "id":77
                     },
                     {
                        "support":"yes",
                        "feature":1144,
                        "version":21,
                        "id":50
                     },
                     {
                        "support":"yes",
                        "feature":1144,
                        "version":73,
                        "id":51
                     },
                     {
                        "id":52,
                        "version":159,
                        "feature":1144,
                        "footnote":"Natural inline elements only",
                        "support":"yes",
                        "footnote_id":[
                           "4",
                           9985,
                           9988
                        ]
                     },
                     {
                        "support":"yes",
                        "feature":1144,
                        "version":176,
                        "id":53
                     },
                     {
                        "support":"yes",
                        "feature":1144,
                        "version":236,
                        "id":54
                     },
                     {
                        "support":"yes",
                        "feature":1148,
                        "version":21,
                        "id":68
                     },
                     {
                        "support":"yes",
                        "feature":1148,
                        "version":68,
                        "id":69
                     },
                     {
                        "support":"yes",
                        "feature":1148,
                        "version":160,
                        "id":70
                     },
                     {
                        "support":"yes",
                        "feature":1148,
                        "version":176,
                        "id":71
                     },
                     {
                        "support":"yes",
                        "feature":1148,
                        "version":236,
                        "id":72
                     },
                     {
                        "id":79,
                        "version":21,
                        "feature":1151,
                        "footnote":"Not before inline-elements",
                        "support":"yes",
                        "footnote_id":[
                           "5",
                           10286,
                           10289
                        ]
                     },
                     {
                        "support":"no",
                        "feature":1151,
                        "version":67,
                        "id":82
                     },
                     {
                        "support":"yes",
                        "feature":1151,
                        "version":162,
                        "id":83
                     },
                     {
                        "support":"yes",
                        "feature":1151,
                        "version":176,
                        "id":84
                     },
                     {
                        "id":85,
                        "version":236,
                        "feature":1151,
                        "footnote":"Not before inline-elements",
                        "support":"yes",
                        "footnote_id":[
                           "5",
                           10404,
                           10407
                        ]
                     },
                     {
                        "support":"yes",
                        "feature":1151,
                        "version":24,
                        "id":81
                     },
                     {
                        "support":"no",
                        "feature":1151,
                        "version":52,
                        "id":80
                     },
                     {
                        "support":"yes",
                        "feature":1151,
                        "version":246,
                        "id":86
                     },
                     {
                        "support":"yes",
                        "feature":1147,
                        "version":21,
                        "id":63
                     },
                     {
                        "support":"yes",
                        "feature":1147,
                        "version":73,
                        "id":64
                     },
                     {
                        "support":"yes",
                        "feature":1147,
                        "version":162,
                        "id":65
                     },
                     {
                        "support":"yes",
                        "feature":1147,
                        "version":176,
                        "id":66
                     },
                     {
                        "support":"yes",
                        "feature":1147,
                        "version":236,
                        "id":67
                     },
                     {
                        "support":"yes",
                        "feature":1152,
                        "version":21,
                        "id":87
                     },
                     {
                        "support":"yes",
                        "feature":1152,
                        "version":68,
                        "id":88
                     },
                     {
                        "support":"yes",
                        "feature":1152,
                        "version":162,
                        "id":89
                     },
                     {
                        "support":"yes",
                        "feature":1152,
                        "version":176,
                        "id":90
                     },
                     {
                        "support":"yes",
                        "feature":1152,
                        "version":236,
                        "id":91
                     },
                     {
                        "prefix":"-webkit",
                        "support":"yes",
                        "feature":1142,
                        "version":41,
                        "id":42
                     },
                     {
                        "id":43,
                        "version":268,
                        "feature":1142,
                        "footnote":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28.",
                        "support":"yes",
                        "footnote_id":[
                           "1",
                           11198,
                           11201
                        ]
                     },
                     {
                        "support":"yes",
                        "feature":1142,
                        "version":89,
                        "id":44
                     },
                     {
                        "support":"yes",
                        "feature":1142,
                        "version":165,
                        "id":115
                     },
                     {
                        "support":"yes",
                        "feature":1142,
                        "version":202,
                        "id":46
                     },
                     {
                        "prefix":"-webkit",
                        "support":"yes",
                        "feature":1142,
                        "version":250,
                        "id":116
                     },
                     {
                        "prefix":"-webkit",
                        "support":"yes",
                        "feature":1145,
                        "version":41,
                        "id":55
                     },
                     {
                        "id":56,
                        "version":268,
                        "feature":1145,
                        "footnote":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28.",
                        "support":"yes",
                        "footnote_id":[
                           "1",
                           11462,
                           11465
                        ]
                     },
                     {
                        "support":"yes",
                        "feature":1145,
                        "version":89,
                        "id":57
                     },
                     {
                        "support":"yes",
                        "feature":1145,
                        "version":165,
                        "id":117
                     },
                     {
                        "support":"yes",
                        "feature":1145,
                        "version":202,
                        "id":59
                     },
                     {
                        "prefix":"-webkit",
                        "support":"yes",
                        "feature":1145,
                        "version":250,
                        "id":118
                     },
                     {
                        "support":"no",
                        "feature":1143,
                        "version":67,
                        "id":48
                     },
                     {
                        "prefix":"-ms",
                        "support":"yes",
                        "feature":1143,
                        "version":164,
                        "id":49
                     },
                     {
                        "support":"no",
                        "feature":1146,
                        "version":67,
                        "id":61
                     },
                     {
                        "prefix":"-ms",
                        "support":"yes",
                        "feature":1146,
                        "version":164,
                        "id":62
                     },
                     {
                        "id":78,
                        "version":275,
                        "feature":1150,
                        "footnote":"CSS Ruby support is behind pref \"layout.css.ruby.enabled\". The user has to change this pref to true to activate this.",
                        "support":"yes",
                        "footnote_id":[
                           "3",
                           12303,
                           12306
                        ]
                     },
                     {
                        "support":"no",
                        "feature":1141,
                        "version":20,
                        "id":37
                     },
                     {
                        "id":38,
                        "version":279,
                        "feature":1141,
                        "footnote":"In Firefox 36, it the preference governing this feature was off by default.",
                        "support":"yes",
                        "footnote_id":[
                           "2",
                           12536,
                           12539
                        ]
                     },
                     {
                        "support":"no",
                        "feature":1141,
                        "version":151,
                        "id":39
                     },
                     {
                        "support":"no",
                        "feature":1141,
                        "version":166,
                        "id":40
                     },
                     {
                        "support":"no",
                        "feature":1141,
                        "version":235,
                        "id":41
                     }
                  ]
               },
               {
                  "browsers":[
                     {
                        "name":"Android",
                        "slug":"android",
                        "id":1
                     },
                     {
                        "name":"Firefox Mobile",
                        "slug":"firefox_mobile",
                        "id":7
                     },
                     {
                        "name":"IE Mobile",
                        "slug":"ie_mobile",
                        "id":9
                     },
                     {
                        "name":"Opera Mobile",
                        "slug":"opera_mobile",
                        "id":13
                     },
                     {
                        "name":"Safari Mobile",
                        "slug":"safari_mobile",
                        "id":15
                     }
                  ],
                  "versions":[
                     {
                        "browser":1,
                        "version":"4.4",
                        "id":14
                     },
                     {
                        "browser":15,
                        "version":"7.0",
                        "id":265
                     }
                  ],
                  "name":"mobile",
                  "features":[
                     {
                        "slug":"web-css-display_basic_support",
                        "name":"Basic support",
                        "id":1140
                     }
                  ],
                  "supports":[
                     {
                        "support":"yes",
                        "feature":1140,
                        "version":14,
                        "id":113
                     },
                     {
                        "prefix":"-webkit",
                        "support":"yes",
                        "feature":1140,
                        "version":265,
                        "id":114
                     }
                  ]
               }
            ],
            "issues":[

            ],
            "footnotes":null
         }
      }
   }
}
