window.displayPayload = {
   "features":{
      "id":"730",
      "slug":"web-css-display",
      "mdn_uri":{
         "en":"https://developer.mozilla.org/en-US/docs/Web/CSS/display",
         "de":"https://developer.mozilla.org/de/docs/Web/CSS/display",
         "es":"https://developer.mozilla.org/es/docs/Web/CSS/display",
         "fr":"https://developer.mozilla.org/fr/docs/Web/CSS/display",
         "ja":"https://developer.mozilla.org/ja/docs/Web/CSS/display",
         "pl":"https://developer.mozilla.org/pl/docs/Web/CSS/display",
         "pt-BR":"https://developer.mozilla.org/pt-BR/docs/Web/CSS/display",
         "pt-PT":"https://developer.mozilla.org/pt-PT/docs/Web/CSS/display",
         "ru":"https://developer.mozilla.org/ru/docs/Web/CSS/display",
         "zh-CN":"https://developer.mozilla.org/zh-CN/docs/CSS/display"
      },
      "experimental":false,
      "standardized":true,
      "stable":true,
      "obsolete":false,
      "name":{
         "en":"display"
      },
      "links":{
         "sections":[
            "151_#display",
            "37_#display",
            "27_#grid-declaration0",
            "23_#flex-containers",
            "10_visuren.html#display-prop",
            "9_#display"
         ],
         "supports":[

         ],
         "parent":"581",
         "children":[

         ]
      }
   },
   "linked":{
      "browsers":[
         {
            "id":"1",
            "slug":"android",
            "name":{
               "en":"Android"
            },
            "note":null
         },
         {
            "id":"3",
            "slug":"chrome",
            "name":{
               "en":"Chrome"
            },
            "note":null
         },
         {
            "id":"6",
            "slug":"firefox",
            "name":{
               "en":"Firefox"
            },
            "note":null
         },
         {
            "id":"7",
            "slug":"firefox_mobile",
            "name":{
               "en":"Firefox Mobile"
            },
            "note":null
         },
         {
            "id":"9",
            "slug":"ie_mobile",
            "name":{
               "en":"IE Mobile"
            },
            "note":null
         },
         {
            "id":"10",
            "slug":"internet_explorer",
            "name":{
               "en":"Internet Explorer"
            },
            "note":null
         },
         {
            "id":"11",
            "slug":"opera",
            "name":{
               "en":"Opera"
            },
            "note":null
         },
         {
            "id":"13",
            "slug":"opera_mobile",
            "name":{
               "en":"Opera Mobile"
            },
            "note":null
         },
         {
            "id":"14",
            "slug":"safari",
            "name":{
               "en":"Safari"
            },
            "note":null
         },
         {
            "id":"15",
            "slug":"safari_mobile",
            "name":{
               "en":"Safari Mobile"
            },
            "note":null
         }
      ],
      "versions":[
         {
            "id":"20",
            "version":null,
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"21",
            "version":"1.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":1,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"24",
            "version":"4.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":4,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"41",
            "version":"21.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":21,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"52",
            "version":"32.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":32,
            "links":{
               "browser":"3"
            }
         },
         {
            "id":"67",
            "version":null,
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"68",
            "version":"1.0",
            "release_day":"2004-11-09",
            "retirement_day":"2005-11-29",
            "status":"retired",
            "release_notes_uri":null,
            "note":null,
            "order":1,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"73",
            "version":"3.0",
            "release_day":"2008-06-17",
            "retirement_day":"2009-06-30",
            "status":"retired",
            "release_notes_uri":{
               "ko":"https://developer.mozilla.org/ko/Firefox/Releases/3",
               "ja":"https://developer.mozilla.org/ja/Firefox/Releases/3",
               "en":"https://developer.mozilla.org/en/Firefox/Releases/3",
               "ru":"https://developer.mozilla.org/ru/docs/Firefox_3_for_developers",
               "pl":"https://developer.mozilla.org/pl/Firefox/Releases/3",
               "de":"https://developer.mozilla.org/de/docs/Firefox_3_f%C3%BCr_Entwickler",
               "fr":"https://developer.mozilla.org/fr/Firefox/Versions/3",
               "zh-TW":"https://developer.mozilla.org/zh-TW/docs/Firefox_3_for_developers",
               "es":"https://developer.mozilla.org/es/docs/Firefox_3_para_desarrolladores",
               "zh-CN":"https://developer.mozilla.org/zh-CN/Firefox/Releases/3",
               "pt-PT":"https://developer.mozilla.org/pt-PT/Firefox/Releases/3"
            },
            "note":null,
            "order":4,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"151",
            "version":null,
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"156",
            "version":"4.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":5,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"159",
            "version":"5.5",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":8,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"160",
            "version":"6.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":9,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"162",
            "version":"8.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":11,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"164",
            "version":"10.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":13,
            "links":{
               "browser":"10"
            }
         },
         {
            "id":"166",
            "version":null,
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"11"
            }
         },
         {
            "id":"176",
            "version":"7.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":10,
            "links":{
               "browser":"11"
            }
         },
         {
            "id":"202",
            "version":"12.50",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":36,
            "links":{
               "browser":"11"
            }
         },
         {
            "id":"235",
            "version":null,
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":0,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"236",
            "version":"1.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":1,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"246",
            "version":"5.0",
            "release_day":null,
            "retirement_day":null,
            "status":"unknown",
            "release_notes_uri":null,
            "note":null,
            "order":11,
            "links":{
               "browser":"14"
            }
         },
         {
            "id":"268",
            "version":"18.0",
            "release_day":"2013-01-08",
            "retirement_day":"2013-02-19",
            "status":"retired",
            "release_notes_uri":{
               "ko":"https://developer.mozilla.org/ko/Firefox/Releases/18",
               "ja":"https://developer.mozilla.org/ja/Firefox/Releases/18",
               "en":"https://developer.mozilla.org/en/Firefox/Releases/18",
               "ru":"https://developer.mozilla.org/ru/Firefox/Releases/18",
               "pl":"https://developer.mozilla.org/pl/Firefox/Releases/18",
               "de":"https://developer.mozilla.org/de/Firefox/Releases/18",
               "fr":"https://developer.mozilla.org/fr/Firefox/Versions/18",
               "zh-TW":"https://developer.mozilla.org/zh-TW/Firefox/Releases/18",
               "es":"https://developer.mozilla.org/es/Firefox/Releases/18",
               "zh-CN":"https://developer.mozilla.org/zh-CN/Firefox/Releases/18",
               "pt-PT":"https://developer.mozilla.org/pt-PT/Firefox/Releases/18"
            },
            "note":null,
            "order":21,
            "links":{
               "browser":"6"
            }
         },
         {
            "id":"279",
            "version":"37.0",
            "release_day":null,
            "retirement_day":null,
            "status":"future",
            "release_notes_uri":{
               "en":"https://developer.mozilla.org/en-US/Firefox/Releases/36"
            },
            "note":null,
            "order":40,
            "links":{
               "browser":"6"
            }
         }
      ],
      "supports":[
         {
            "id":"__contents-151",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"151",
               "feature":"_contents"
            }
         },
         {
            "id":"__contents-166",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"166",
               "feature":"_contents"
            }
         },
         {
            "id":"__contents-20",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"20",
               "feature":"_contents"
            }
         },
         {
            "id":"__contents-235",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"235",
               "feature":"_contents"
            }
         },
         {
            "id":"__contents-279",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":{
               "en":"In Firefox 36, it the preference governing this feature was off by default."
            },
            "links":{
               "version":"279",
               "feature":"_contents"
            }
         },
         {
            "id":"__flex-151",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"151",
               "feature":"_flex"
            }
         },
         {
            "id":"__flex-202",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"202",
               "feature":"_flex"
            }
         },
         {
            "id":"__flex-235",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"235",
               "feature":"_flex"
            }
         },
         {
            "id":"__flex-268",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":{
               "en":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28."
            },
            "links":{
               "version":"268",
               "feature":"_flex"
            }
         },
         {
            "id":"__flex-41",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"41",
               "feature":"_flex"
            }
         },
         {
            "id":"__grid-164",
            "support":"yes",
            "prefix":"-ms",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"164",
               "feature":"_grid"
            }
         },
         {
            "id":"__grid-67",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"67",
               "feature":"_grid"
            }
         },
         {
            "id":"__inline-block-159",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"159",
               "feature":"_inline-block"
            }
         },
         {
            "id":"__inline-block-176",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"176",
               "feature":"_inline-block"
            }
         },
         {
            "id":"__inline-block-21",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"21",
               "feature":"_inline-block"
            }
         },
         {
            "id":"__inline-block-236",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"236",
               "feature":"_inline-block"
            }
         },
         {
            "id":"__inline-block-73",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"73",
               "feature":"_inline-block"
            }
         },
         {
            "id":"__inline-flex-151",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"151",
               "feature":"_inline-flex"
            }
         },
         {
            "id":"__inline-flex-202",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"202",
               "feature":"_inline-flex"
            }
         },
         {
            "id":"__inline-flex-235",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"235",
               "feature":"_inline-flex"
            }
         },
         {
            "id":"__inline-flex-268",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":{
               "en":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28."
            },
            "links":{
               "version":"268",
               "feature":"_inline-flex"
            }
         },
         {
            "id":"__inline-flex-41",
            "support":"yes",
            "prefix":"-webkit",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"41",
               "feature":"_inline-flex"
            }
         },
         {
            "id":"__inline-grid-164",
            "support":"yes",
            "prefix":"-ms",
            "prefix_mandatory":true,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"164",
               "feature":"_inline-grid"
            }
         },
         {
            "id":"__inline-grid-67",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"67",
               "feature":"_inline-grid"
            }
         },
         {
            "id":"__inline-table-162",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"162",
               "feature":"_inline-table"
            }
         },
         {
            "id":"__inline-table-176",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"176",
               "feature":"_inline-table"
            }
         },
         {
            "id":"__inline-table-21",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"21",
               "feature":"_inline-table"
            }
         },
         {
            "id":"__inline-table-236",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"236",
               "feature":"_inline-table"
            }
         },
         {
            "id":"__inline-table-73",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"73",
               "feature":"_inline-table"
            }
         },
         {
            "id":"__list-item-160",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"160",
               "feature":"_list-item"
            }
         },
         {
            "id":"__list-item-176",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"176",
               "feature":"_list-item"
            }
         },
         {
            "id":"__list-item-21",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"21",
               "feature":"_list-item"
            }
         },
         {
            "id":"__list-item-236",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"236",
               "feature":"_list-item"
            }
         },
         {
            "id":"__list-item-68",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"68",
               "feature":"_list-item"
            }
         },
         {
            "id":"__none, inline and block-156",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"156",
               "feature":"_none, inline and block"
            }
         },
         {
            "id":"__none, inline and block-176",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"176",
               "feature":"_none, inline and block"
            }
         },
         {
            "id":"__none, inline and block-21",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"21",
               "feature":"_none, inline and block"
            }
         },
         {
            "id":"__none, inline and block-236",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"236",
               "feature":"_none, inline and block"
            }
         },
         {
            "id":"__none, inline and block-68",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"68",
               "feature":"_none, inline and block"
            }
         },
         {
            "id":"__ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container-67",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"67",
               "feature":"_ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container"
            }
         },
         {
            "id":"__run-in-162",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"162",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-176",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"176",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-21",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"21",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-236",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"236",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-24",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"24",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-246",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"246",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-52",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"52",
               "feature":"_run-in"
            }
         },
         {
            "id":"__run-in-67",
            "support":"no",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"67",
               "feature":"_run-in"
            }
         },
         {
            "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-162",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"162",
               "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption"
            }
         },
         {
            "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-176",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"176",
               "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption"
            }
         },
         {
            "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-21",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"21",
               "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption"
            }
         },
         {
            "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-236",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"236",
               "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption"
            }
         },
         {
            "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-68",
            "support":"yes",
            "prefix":null,
            "prefix_mandatory":false,
            "alternate_name":null,
            "alternate_mandatory":false,
            "requires_config":null,
            "default_config":null,
            "protected":false,
            "note":null,
            "footnote":null,
            "links":{
               "version":"68",
               "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption"
            }
         }
      ],
      "maturities":[
         {
            "id":"1",
            "slug":"WD",
            "name":{
               "ru":"\u0420\u0430\u0431\u043e\u0447\u0438\u0439 \u0447\u0435\u0440\u043d\u043e\u0432\u0438\u043a",
               "en":"Working Draft",
               "ja":"\u8349\u6848",
               "de":"Arbeitsentwurf"
            }
         },
         {
            "id":"2",
            "slug":"CR",
            "name":{
               "ru":"\u041a\u0430\u043d\u0434\u0438\u0434\u0430\u0442 \u0432 \u0440\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u0438",
               "en":"Candidate Recommendation",
               "ja":"\u52e7\u544a\u5019\u88dc",
               "de":"Anw\u00e4rter Empfehlung"
            }
         },
         {
            "id":"4",
            "slug":"REC",
            "name":{
               "ru":"\u0420\u0435\u043a\u043e\u043c\u0435\u043d\u0434\u0430\u0446\u0438\u044f",
               "en":"Recommendation",
               "ja":"\u52e7\u544a",
               "de":"Empfehlung"
            }
         }
      ],
      "specifications":[
         {
            "id":"9",
            "slug":"css1",
            "mdn_key":"CSS1",
            "name":{
               "en":"CSS Level&nbsp;1"
            },
            "uri":{
               "en":"http://www.w3.org/TR/CSS1/"
            },
            "links":{
               "maturity":"4",
               "sections":[
                  "2"
               ]
            }
         },
         {
            "id":"10",
            "slug":"css2_1",
            "mdn_key":"CSS2.1",
            "name":{
               "en":"CSS Level&nbsp;2 (Revision&nbsp;1)"
            },
            "uri":{
               "en":"http://www.w3.org/TR/CSS2/"
            },
            "links":{
               "maturity":"4",
               "sections":[
                  "3"
               ]
            }
         },
         {
            "id":"23",
            "slug":"css3_flexbox",
            "mdn_key":"CSS3 Flexbox",
            "name":{
               "en":"CSS Flexible Box Layout Module"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css3-flexbox/"
            },
            "links":{
               "maturity":"2",
               "sections":[

               ]
            }
         },
         {
            "id":"27",
            "slug":"css3_grid",
            "mdn_key":"CSS3 Grid",
            "name":{
               "en":"CSS Grid Layout"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css-grid/"
            },
            "links":{
               "maturity":"1",
               "sections":[

               ]
            }
         },
         {
            "id":"37",
            "slug":"css3_ruby",
            "mdn_key":"CSS3 Ruby",
            "name":{
               "en":"CSS Ruby Layout Module Level&nbsp;1"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css-ruby/"
            },
            "links":{
               "maturity":"1",
               "sections":[

               ]
            }
         },
         {
            "id":"151",
            "slug":"css3_display",
            "mdn_key":"CSS3 Display",
            "name":{
               "en":"CSS Display Module Level&nbsp;3"
            },
            "uri":{
               "en":"http://dev.w3.org/csswg/css-display/"
            },
            "links":{
               "maturity":"1",
               "sections":[

               ]
            }
         }
      ],
      "sections":[
         {
            "id":"10_visuren.html#display-prop",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"visuren.html#display-prop"
            },
            "note":{
               "en":"Added the table model values and <code>inline-block<em>.</em></code>"
            },
            "links":{
               "specification":"10"
            }
         },
         {
            "id":"151_#display",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#display"
            },
            "note":{
               "en":"Added the <code>run-in</code> and <code>contents</code> values."
            },
            "links":{
               "specification":"151"
            }
         },
         {
            "id":"23_#flex-containers",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#flex-containers"
            },
            "note":{
               "en":"Added the flexible box model values."
            },
            "links":{
               "specification":"23"
            }
         },
         {
            "id":"27_#grid-declaration0",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#grid-declaration0"
            },
            "note":{
               "en":"Added the grid box model values."
            },
            "links":{
               "specification":"27"
            }
         },
         {
            "id":"37_#display",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#display"
            },
            "note":{
               "en":"Added the <code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, and <code>ruby-text-container </code>"
            },
            "links":{
               "specification":"37"
            }
         },
         {
            "id":"9_#display",
            "number":null,
            "name":{
               "en":"display"
            },
            "subpath":{
               "en":"#display"
            },
            "note":{
               "en":"Basic values: <code>none</code>, <code>block</code>, <code>inline</code>, and <code>list-item</code>."
            },
            "links":{
               "specification":"9"
            }
         }
      ],
      "features":[
         {
            "id":"_basic support",
            "slug":"web-css-display_basic_support",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"Basic support"
            },
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_contents",
            "slug":"web-css-display_contents",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"contents",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_flex",
            "slug":"web-css-display_flex",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"flex",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_grid",
            "slug":"web-css-display_grid",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"grid",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_inline-block",
            "slug":"web-css-display_inline-block",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-block",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_inline-flex",
            "slug":"web-css-display_inline-flex",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-flex",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_inline-grid",
            "slug":"web-css-display_inline-grid",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-grid",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_inline-table",
            "slug":"web-css-display_inline-table",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"inline-table",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_list-item",
            "slug":"web-css-display_list-item",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"list-item",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_none, inline and block",
            "slug":"web-css-display_none_inline_and_block",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"<code>none</code>, <code>inline</code> and <code>block</code>"
            },
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container",
            "slug":"web-css-display_ruby_ruby-base_ruby-text_ruby-base",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"<code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, <code>ruby-text-container</code>"
            },
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_run-in",
            "slug":"web-css-display_run-in",
            "mdn_uri":null,
            "experimental":true,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":"run-in",
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         },
         {
            "id":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
            "slug":"web-css-display_table_table-cell_table-column_tabl",
            "mdn_uri":null,
            "experimental":false,
            "standardized":true,
            "stable":true,
            "obsolete":false,
            "name":{
               "en":"<code>table</code>, <code>table-cell</code>, <code>table-column</code>, <code>table-column-group</code>, <code>table-header-group</code>, <code>table-row-group</code>, <code>table-footer-group</code>, <code>table-row</code>, and <code>table-caption</code>"
            },
            "links":{
               "sections":[

               ],
               "supports":[

               ],
               "parent":"730",
               "children":[

               ]
            }
         }
      ]
   },
   "meta":{
      "compat_table":{
         "supports":{
            "730":{

            },
            "_none, inline and block":{
               "3":[
                  "__none, inline and block-21"
               ],
               "6":[
                  "__none, inline and block-68"
               ],
               "10":[
                  "__none, inline and block-156"
               ],
               "11":[
                  "__none, inline and block-176"
               ],
               "14":[
                  "__none, inline and block-236"
               ]
            },
            "_inline-block":{
               "3":[
                  "__inline-block-21"
               ],
               "6":[
                  "__inline-block-73"
               ],
               "10":[
                  "__inline-block-159"
               ],
               "11":[
                  "__inline-block-176"
               ],
               "14":[
                  "__inline-block-236"
               ]
            },
            "_list-item":{
               "3":[
                  "__list-item-21"
               ],
               "6":[
                  "__list-item-68"
               ],
               "10":[
                  "__list-item-160"
               ],
               "11":[
                  "__list-item-176"
               ],
               "14":[
                  "__list-item-236"
               ]
            },
            "_run-in":{
               "3":[
                  "__run-in-21",
                  "__run-in-24",
                  "__run-in-52"
               ],
               "6":[
                  "__run-in-67"
               ],
               "10":[
                  "__run-in-162"
               ],
               "11":[
                  "__run-in-176"
               ],
               "14":[
                  "__run-in-236",
                  "__run-in-246"
               ]
            },
            "_inline-table":{
               "3":[
                  "__inline-table-21"
               ],
               "6":[
                  "__inline-table-73"
               ],
               "10":[
                  "__inline-table-162"
               ],
               "11":[
                  "__inline-table-176"
               ],
               "14":[
                  "__inline-table-236"
               ]
            },
            "_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption":{
               "3":[
                  "__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-21"
               ],
               "6":[
                  "__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-68"
               ],
               "10":[
                  "__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-162"
               ],
               "11":[
                  "__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-176"
               ],
               "14":[
                  "__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-236"
               ]
            },
            "_flex":{
               "3":[
                  "__flex-41"
               ],
               "6":[
                  "__flex-268"
               ],
               "10":[
                  "__flex-151"
               ],
               "11":[
                  "__flex-202"
               ],
               "14":[
                  "__flex-235"
               ]
            },
            "_inline-flex":{
               "3":[
                  "__inline-flex-41"
               ],
               "6":[
                  "__inline-flex-268"
               ],
               "10":[
                  "__inline-flex-151"
               ],
               "11":[
                  "__inline-flex-202"
               ],
               "14":[
                  "__inline-flex-235"
               ]
            },
            "_grid":{
               "6":[
                  "__grid-67"
               ],
               "10":[
                  "__grid-164"
               ]
            },
            "_inline-grid":{
               "6":[
                  "__inline-grid-67"
               ],
               "10":[
                  "__inline-grid-164"
               ]
            },
            "_ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container":{
               "6":[
                  "__ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container-67"
               ]
            },
            "_contents":{
               "3":[
                  "__contents-20"
               ],
               "6":[
                  "__contents-279"
               ],
               "10":[
                  "__contents-151"
               ],
               "11":[
                  "__contents-166"
               ],
               "14":[
                  "__contents-235"
               ]
            },
            "_basic support":{

            }
         },
         "tabs":[
            {
               "name":{
                  "en":"Desktop Browsers"
               },
               "browsers":[
                  "3",
                  "6",
                  "10",
                  "11",
                  "14"
               ]
            },
            {
               "name":{
                  "en":"Mobile Browsers"
               },
               "browsers":[
                  "1",
                  "7",
                  "9",
                  "13",
                  "15"
               ]
            }
         ],
         "pagination":{

         },
         "languages":[
            "en",
            "de",
            "es",
            "fr",
            "ja",
            "pl",
            "pt-BR",
            "pt-PT",
            "ru",
            "zh-CN"
         ],
         "footnotes":{
            "__flex-268":1,
            "__inline-flex-268":2,
            "__contents-279":3
         }
      },
      "scrape":{
         "phase":"Starting Import",
         "errors":[
            "<div><p>In Specifications section, expected &lt;h2 id=&quot;Specifications&quot;&gt;, actual id=&quot;Browser_Compatibility&quot;</p><p>Context:<pre>198 &lt;/pre&gt;\n199 \n200 &lt;h2 id=&quot;Browser_Compatibility&quot; name=&quot;Browser_Compatibility&quot;&gt;Specifications&lt;/h2&gt;\n***     ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                \n201 \n202 &lt;table class=&quot;standard-table&quot;&gt;\n</pre></p></div>",
            "<div><p>In Specifications section, expected &lt;h2 name=&quot;Specifications&quot;&gt; or no name attribute, actual name=&quot;Browser_Compatibility&quot;</p><p>Context:<pre>198 &lt;/pre&gt;\n199 \n200 &lt;h2 id=&quot;Browser_Compatibility&quot; name=&quot;Browser_Compatibility&quot;&gt;Specifications&lt;/h2&gt;\n***                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                    \n201 \n202 &lt;table class=&quot;standard-table&quot;&gt;\n</pre></p></div>",
            "<div><p>Unknown support text &quot;(-7.0)&quot;</p><p>Context:<pre>269    &lt;td&gt;1.0&lt;/td&gt;\n270    &lt;td&gt;{{CompatGeckoDesktop(&quot;1.9&quot;)}}&lt;/td&gt;\n271    &lt;td&gt;5.5 (-7.0)&lt;br&gt;\n***            ^^^^^^    \n272     natural inline elements only&lt;/td&gt;\n273    &lt;td&gt;7.0&lt;/td&gt;\n</pre></p></div>",
            "<div><p>Unknown support text &quot;natural inline elements only&quot;</p><p>Context:<pre>270    &lt;td&gt;{{CompatGeckoDesktop(&quot;1.9&quot;)}}&lt;/td&gt;\n271    &lt;td&gt;5.5 (-7.0)&lt;br&gt;\n272     natural inline elements only&lt;/td&gt;\n***     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^     \n273    &lt;td&gt;7.0&lt;/td&gt;\n274    &lt;td&gt;1.0 (85)&lt;/td&gt;\n</pre></p></div>",
            "<div><p>Unknown support text &quot;Not before inline-elements&quot;</p><p>Context:<pre>285    &lt;td rowspan=&quot;2&quot;&gt;&lt;code&gt;run-in&lt;/code&gt; {{experimental_inline}}&lt;/td&gt;\n286    &lt;td&gt;1.0&lt;br&gt;\n287     Not before inline-elements&lt;/td&gt;\n***     ^^^^^^^^^^^^^^^^^^^^^^^^^^     \n288    &lt;td rowspan=&quot;2&quot;&gt;{{CompatNo}}&lt;/td&gt;\n289    &lt;td rowspan=&quot;2&quot;&gt;8.0&lt;/td&gt;\n</pre></p></div>",
            "<div><p>Unknown support text &quot;Not before inline-elements&quot;</p><p>Context:<pre>290    &lt;td rowspan=&quot;2&quot;&gt;7.0&lt;/td&gt;\n291    &lt;td&gt;1.0 (85)&lt;br&gt;\n292     Not before inline-elements&lt;/td&gt;\n***     ^^^^^^^^^^^^^^^^^^^^^^^^^^     \n293   &lt;/tr&gt;\n294   &lt;tr&gt;\n</pre></p></div>",
            "<div><p>Unknown support text &quot;(behind a pref)&quot;</p><p>Context:<pre>319    &lt;td&gt;&lt;code&gt;flex&lt;/code&gt;&lt;/td&gt;\n320    &lt;td&gt;21.0{{property_prefix(&quot;-webkit&quot;)}}&lt;/td&gt;\n321    &lt;td&gt;{{CompatGeckoDesktop(&quot;18.0&quot;)}}(behind a pref) [1]&lt;/td&gt;\n***                                      ^^^^^^^^^^^^^^^^        \n322    &lt;td&gt;{{CompatNo}}&lt;/td&gt;\n323    &lt;td&gt;12.50&lt;/td&gt;\n</pre></p></div>",
            "<div><p>Unknown support text &quot;(behind a pref)&quot;</p><p>Context:<pre>327    &lt;td&gt;&lt;code&gt;inline-flex&lt;/code&gt;&lt;/td&gt;\n328    &lt;td&gt;21.0{{property_prefix(&quot;-webkit&quot;)}}&lt;/td&gt;\n329    &lt;td&gt;{{CompatGeckoDesktop(&quot;18.0&quot;)}}(behind a pref) [1]&lt;/td&gt;\n***                                      ^^^^^^^^^^^^^^^^        \n330    &lt;td&gt;{{CompatNo}}&lt;/td&gt;\n331    &lt;td&gt;12.50&lt;/td&gt;\n</pre></p></div>"
         ],
         "raw":{
            "locale":"en",
            "specs":[
               {
                  "section.id":null,
                  "section.note":"Added the <code>run-in</code> and <code>contents</code> values.",
                  "section.name":"display",
                  "specification.mdn_key":"CSS3 Display",
                  "specification.id":151,
                  "section.subpath":"#display"
               },
               {
                  "section.id":null,
                  "section.note":"Added the <code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, and <code>ruby-text-container </code>",
                  "section.name":"display",
                  "specification.mdn_key":"CSS3 Ruby",
                  "specification.id":37,
                  "section.subpath":"#display"
               },
               {
                  "section.id":null,
                  "section.note":"Added the grid box model values.",
                  "section.name":"display",
                  "specification.mdn_key":"CSS3 Grid",
                  "specification.id":27,
                  "section.subpath":"#grid-declaration0"
               },
               {
                  "section.id":null,
                  "section.note":"Added the flexible box model values.",
                  "section.name":"display",
                  "specification.mdn_key":"CSS3 Flexbox",
                  "specification.id":23,
                  "section.subpath":"#flex-containers"
               },
               {
                  "section.id":null,
                  "section.note":"Added the table model values and <code>inline-block<em>.</em></code>",
                  "section.name":"display",
                  "specification.mdn_key":"CSS2.1",
                  "specification.id":10,
                  "section.subpath":"visuren.html#display-prop"
               },
               {
                  "section.id":null,
                  "section.note":"Basic values: <code>none</code>, <code>block</code>, <code>inline</code>, and <code>list-item</code>.",
                  "section.name":"display",
                  "specification.mdn_key":"CSS1",
                  "specification.id":9,
                  "section.subpath":"#display"
               }
            ],
            "compat":[
               {
                  "supports":[
                     {
                        "id":"__none, inline and block-21",
                        "feature":"_none, inline and block",
                        "support":"yes",
                        "version":21
                     },
                     {
                        "id":"__none, inline and block-68",
                        "feature":"_none, inline and block",
                        "support":"yes",
                        "version":68
                     },
                     {
                        "id":"__none, inline and block-156",
                        "feature":"_none, inline and block",
                        "support":"yes",
                        "version":156
                     },
                     {
                        "id":"__none, inline and block-176",
                        "feature":"_none, inline and block",
                        "support":"yes",
                        "version":176
                     },
                     {
                        "id":"__none, inline and block-236",
                        "feature":"_none, inline and block",
                        "support":"yes",
                        "version":236
                     },
                     {
                        "id":"__inline-block-21",
                        "feature":"_inline-block",
                        "support":"yes",
                        "version":21
                     },
                     {
                        "id":"__inline-block-73",
                        "feature":"_inline-block",
                        "support":"yes",
                        "version":73
                     },
                     {
                        "id":"__inline-block-159",
                        "feature":"_inline-block",
                        "support":"yes",
                        "version":159
                     },
                     {
                        "id":"__inline-block-176",
                        "feature":"_inline-block",
                        "support":"yes",
                        "version":176
                     },
                     {
                        "id":"__inline-block-236",
                        "feature":"_inline-block",
                        "support":"yes",
                        "version":236
                     },
                     {
                        "id":"__list-item-21",
                        "feature":"_list-item",
                        "support":"yes",
                        "version":21
                     },
                     {
                        "id":"__list-item-68",
                        "feature":"_list-item",
                        "support":"yes",
                        "version":68
                     },
                     {
                        "id":"__list-item-160",
                        "feature":"_list-item",
                        "support":"yes",
                        "version":160
                     },
                     {
                        "id":"__list-item-176",
                        "feature":"_list-item",
                        "support":"yes",
                        "version":176
                     },
                     {
                        "id":"__list-item-236",
                        "feature":"_list-item",
                        "support":"yes",
                        "version":236
                     },
                     {
                        "id":"__run-in-21",
                        "feature":"_run-in",
                        "support":"yes",
                        "version":21
                     },
                     {
                        "id":"__run-in-67",
                        "feature":"_run-in",
                        "support":"no",
                        "version":67
                     },
                     {
                        "id":"__run-in-162",
                        "feature":"_run-in",
                        "support":"yes",
                        "version":162
                     },
                     {
                        "id":"__run-in-176",
                        "feature":"_run-in",
                        "support":"yes",
                        "version":176
                     },
                     {
                        "id":"__run-in-236",
                        "feature":"_run-in",
                        "support":"yes",
                        "version":236
                     },
                     {
                        "id":"__run-in-24",
                        "feature":"_run-in",
                        "support":"yes",
                        "version":24
                     },
                     {
                        "id":"__run-in-52",
                        "feature":"_run-in",
                        "support":"no",
                        "version":52
                     },
                     {
                        "id":"__run-in-246",
                        "feature":"_run-in",
                        "support":"yes",
                        "version":246
                     },
                     {
                        "id":"__inline-table-21",
                        "feature":"_inline-table",
                        "support":"yes",
                        "version":21
                     },
                     {
                        "id":"__inline-table-73",
                        "feature":"_inline-table",
                        "support":"yes",
                        "version":73
                     },
                     {
                        "id":"__inline-table-162",
                        "feature":"_inline-table",
                        "support":"yes",
                        "version":162
                     },
                     {
                        "id":"__inline-table-176",
                        "feature":"_inline-table",
                        "support":"yes",
                        "version":176
                     },
                     {
                        "id":"__inline-table-236",
                        "feature":"_inline-table",
                        "support":"yes",
                        "version":236
                     },
                     {
                        "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-21",
                        "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
                        "support":"yes",
                        "version":21
                     },
                     {
                        "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-68",
                        "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
                        "support":"yes",
                        "version":68
                     },
                     {
                        "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-162",
                        "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
                        "support":"yes",
                        "version":162
                     },
                     {
                        "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-176",
                        "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
                        "support":"yes",
                        "version":176
                     },
                     {
                        "id":"__table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption-236",
                        "feature":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
                        "support":"yes",
                        "version":236
                     },
                     {
                        "id":"__flex-41",
                        "feature":"_flex",
                        "support":"yes",
                        "prefix":"-webkit",
                        "version":41
                     },
                     {
                        "id":"__flex-268",
                        "support":"yes",
                        "footnote":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28.",
                        "feature":"_flex",
                        "footnote_id":[
                           "1",
                           11380,
                           11383
                        ],
                        "version":268
                     },
                     {
                        "id":"__flex-151",
                        "feature":"_flex",
                        "support":"no",
                        "version":151
                     },
                     {
                        "id":"__flex-202",
                        "feature":"_flex",
                        "support":"yes",
                        "version":202
                     },
                     {
                        "id":"__flex-235",
                        "feature":"_flex",
                        "support":"no",
                        "version":235
                     },
                     {
                        "id":"__inline-flex-41",
                        "feature":"_inline-flex",
                        "support":"yes",
                        "prefix":"-webkit",
                        "version":41
                     },
                     {
                        "id":"__inline-flex-268",
                        "support":"yes",
                        "footnote":"To activate flexbox support, for Firefox 18 and 19, the user has to change the about:config preference \"layout.css.flexbox.enabled\" to <code>true</code>. Multi-line flexbox are supported since Firefox 28.",
                        "feature":"_inline-flex",
                        "footnote_id":[
                           "1",
                           11609,
                           11612
                        ],
                        "version":268
                     },
                     {
                        "id":"__inline-flex-151",
                        "feature":"_inline-flex",
                        "support":"no",
                        "version":151
                     },
                     {
                        "id":"__inline-flex-202",
                        "feature":"_inline-flex",
                        "support":"yes",
                        "version":202
                     },
                     {
                        "id":"__inline-flex-235",
                        "feature":"_inline-flex",
                        "support":"no",
                        "version":235
                     },
                     {
                        "id":"__grid-67",
                        "feature":"_grid",
                        "support":"no",
                        "version":67
                     },
                     {
                        "id":"__grid-164",
                        "feature":"_grid",
                        "support":"yes",
                        "prefix":"-ms",
                        "version":164
                     },
                     {
                        "id":"__inline-grid-67",
                        "feature":"_inline-grid",
                        "support":"no",
                        "version":67
                     },
                     {
                        "id":"__inline-grid-164",
                        "feature":"_inline-grid",
                        "support":"yes",
                        "prefix":"-ms",
                        "version":164
                     },
                     {
                        "id":"__ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container-67",
                        "feature":"_ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container",
                        "support":"no",
                        "version":67
                     },
                     {
                        "id":"__contents-20",
                        "feature":"_contents",
                        "support":"no",
                        "version":20
                     },
                     {
                        "id":"__contents-279",
                        "support":"yes",
                        "footnote":"In Firefox 36, it the preference governing this feature was off by default.",
                        "feature":"_contents",
                        "footnote_id":[
                           "2",
                           12611,
                           12614
                        ],
                        "version":279
                     },
                     {
                        "id":"__contents-151",
                        "feature":"_contents",
                        "support":"no",
                        "version":151
                     },
                     {
                        "id":"__contents-166",
                        "feature":"_contents",
                        "support":"no",
                        "version":166
                     },
                     {
                        "id":"__contents-235",
                        "feature":"_contents",
                        "support":"no",
                        "version":235
                     }
                  ],
                  "browsers":[
                     {
                        "id":3,
                        "name":"Chrome",
                        "slug":"chrome"
                     },
                     {
                        "id":6,
                        "name":"Firefox",
                        "slug":"firefox"
                     },
                     {
                        "id":10,
                        "name":"Internet Explorer",
                        "slug":"internet_explorer"
                     },
                     {
                        "id":11,
                        "name":"Opera",
                        "slug":"opera"
                     },
                     {
                        "id":14,
                        "name":"Safari",
                        "slug":"safari"
                     }
                  ],
                  "name":"desktop",
                  "features":[
                     {
                        "id":"_none, inline and block",
                        "name":"<code>none</code>, <code>inline</code> and <code>block</code>",
                        "slug":"web-css-display_none_inline_and_block"
                     },
                     {
                        "id":"_inline-block",
                        "slug":"web-css-display_inline-block",
                        "canonical":true,
                        "name":"inline-block"
                     },
                     {
                        "id":"_list-item",
                        "slug":"web-css-display_list-item",
                        "canonical":true,
                        "name":"list-item"
                     },
                     {
                        "id":"_run-in",
                        "experimental":true,
                        "slug":"web-css-display_run-in",
                        "canonical":true,
                        "name":"run-in"
                     },
                     {
                        "id":"_inline-table",
                        "slug":"web-css-display_inline-table",
                        "canonical":true,
                        "name":"inline-table"
                     },
                     {
                        "id":"_table, table-cell, table-column, table-column-group, table-header-group, table-row-group, table-footer-group, table-row, and table-caption",
                        "name":"<code>table</code>, <code>table-cell</code>, <code>table-column</code>, <code>table-column-group</code>, <code>table-header-group</code>, <code>table-row-group</code>, <code>table-footer-group</code>, <code>table-row</code>, and <code>table-caption</code>",
                        "slug":"web-css-display_table_table-cell_table-column_tabl"
                     },
                     {
                        "id":"_flex",
                        "slug":"web-css-display_flex",
                        "canonical":true,
                        "name":"flex"
                     },
                     {
                        "id":"_inline-flex",
                        "slug":"web-css-display_inline-flex",
                        "canonical":true,
                        "name":"inline-flex"
                     },
                     {
                        "id":"_grid",
                        "experimental":true,
                        "slug":"web-css-display_grid",
                        "canonical":true,
                        "name":"grid"
                     },
                     {
                        "id":"_inline-grid",
                        "experimental":true,
                        "slug":"web-css-display_inline-grid",
                        "canonical":true,
                        "name":"inline-grid"
                     },
                     {
                        "id":"_ruby, ruby-base, ruby-text, ruby-base-container, ruby-text-container",
                        "experimental":true,
                        "name":"<code>ruby</code>, <code>ruby-base</code>, <code>ruby-text</code>, <code>ruby-base-container</code>, <code>ruby-text-container</code>",
                        "slug":"web-css-display_ruby_ruby-base_ruby-text_ruby-base"
                     },
                     {
                        "id":"_contents",
                        "experimental":true,
                        "slug":"web-css-display_contents",
                        "canonical":true,
                        "name":"contents"
                     }
                  ],
                  "versions":[
                     {
                        "browser":3,
                        "version":"1.0",
                        "id":21
                     },
                     {
                        "browser":6,
                        "version":"1.0",
                        "id":68
                     },
                     {
                        "browser":10,
                        "version":"4.0",
                        "id":156
                     },
                     {
                        "browser":11,
                        "version":"7.0",
                        "id":176
                     },
                     {
                        "browser":14,
                        "version":"1.0",
                        "id":236
                     },
                     {
                        "browser":6,
                        "version":"3.0",
                        "id":73
                     },
                     {
                        "browser":10,
                        "version":"5.5",
                        "id":159
                     },
                     {
                        "browser":10,
                        "version":"6.0",
                        "id":160
                     },
                     {
                        "browser":6,
                        "version":"",
                        "id":67
                     },
                     {
                        "browser":10,
                        "version":"8.0",
                        "id":162
                     },
                     {
                        "browser":3,
                        "version":"4.0",
                        "id":24
                     },
                     {
                        "browser":3,
                        "version":"32.0",
                        "id":52
                     },
                     {
                        "browser":14,
                        "version":"5.0",
                        "id":246
                     },
                     {
                        "browser":3,
                        "version":"21.0",
                        "id":41
                     },
                     {
                        "browser":6,
                        "version":"18.0",
                        "id":268
                     },
                     {
                        "browser":10,
                        "version":"",
                        "id":151
                     },
                     {
                        "browser":11,
                        "version":"12.50",
                        "id":202
                     },
                     {
                        "browser":14,
                        "version":"",
                        "id":235
                     },
                     {
                        "browser":10,
                        "version":"10.0",
                        "id":164
                     },
                     {
                        "browser":3,
                        "version":"",
                        "id":20
                     },
                     {
                        "browser":6,
                        "version":"37.0",
                        "id":279
                     },
                     {
                        "browser":11,
                        "version":"",
                        "id":166
                     }
                  ]
               },
               {
                  "supports":[

                  ],
                  "browsers":[
                     {
                        "id":1,
                        "name":"Android",
                        "slug":"android"
                     },
                     {
                        "id":7,
                        "name":"Firefox Mobile",
                        "slug":"firefox_mobile"
                     },
                     {
                        "id":9,
                        "name":"IE Mobile",
                        "slug":"ie_mobile"
                     },
                     {
                        "id":13,
                        "name":"Opera Mobile",
                        "slug":"opera_mobile"
                     },
                     {
                        "id":15,
                        "name":"Safari Mobile",
                        "slug":"safari_mobile"
                     }
                  ],
                  "name":"mobile",
                  "features":[
                     {
                        "id":"_basic support",
                        "name":"Basic support",
                        "slug":"web-css-display_basic_support"
                     }
                  ],
                  "versions":[

                  ]
               }
            ],
            "footnotes":{

            },
            "issues":[
               [
                  7900,
                  7927,
                  "In Specifications section, expected <h2 id=\"Specifications\">, actual id=\"Browser_Compatibility\""
               ],
               [
                  7927,
                  7955,
                  "In Specifications section, expected <h2 name=\"Specifications\"> or no name attribute, actual name=\"Browser_Compatibility\""
               ]
            ],
            "errors":[
               [
                  10050,
                  10056,
                  "Unknown support text \"(-7.0)\""
               ],
               [
                  10065,
                  10093,
                  "Unknown support text \"natural inline elements only\""
               ],
               [
                  10399,
                  10425,
                  "Unknown support text \"Not before inline-elements\""
               ],
               [
                  10548,
                  10574,
                  "Unknown support text \"Not before inline-elements\""
               ],
               [
                  11364,
                  11380,
                  "Unknown support text \"(behind a pref)\""
               ],
               [
                  11593,
                  11609,
                  "Unknown support text \"(behind a pref)\""
               ]
            ]
         }
      }
   }
};